- name: Setup software
  hosts: scn4_host
  roles:
    - telegraf-client
  become: yes
  vars_files:
    - "./vars/telegraf_dbconnection_vars.yml"
  vars:
    telegraf_hostname: "scn4"
    telegraf_plugins_base:
      - name: cpu
        options:
          percpu: "false"
          totalcpu: "true"
          fielddrop:
            - "time_*"

- name: Start test Server
  hosts: scn4_host
  become: yes
  roles:
    - too_simple_server
  vars:
    debug: True
    server_port: 80
